In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import geopandas as gpd
import geoplot
import pickle
import geoplot.crs as gcrs
import statsmodels.api as sm

/home/jasonllu/anaconda3/lib/python3.7/site-packages/geopandas/_compat.py:88: UserWarning: The Shapely GEOS version (3.9.0-CAPI-1.14.1) is incompatible with the GEOS version PyGEOS was compiled with (3.9.0-CAPI-1.16.2). Conversions between both will be slow.
  shapely_geos_version, geos_capi_version_string

In [3]:
mount_path = "/mnt/c/Users/jason/Dropbox (MIT)/"
#mount_path = "/Users/shenhaowang/Dropbox (MIT)/project_media_lab_South_Australia/"

In [5]:
social_economic_df = pd.read_csv(mount_path + "/SA data/NATSEM_-_Social_and_Economic_Indicators_-_Indigenous_Indicators_SA2_2016.csv/data6735501229514139095.csv")

In [6]:
social_economic_df = social_economic_df.dropna()

In [7]:
social_economic_df.head()

,perc_indig_age_0_14,perc_indig_hsld_equiv_inc_less_than_300,perc_indig_rent_oth_dwl,perc_indig_no_vehicle_in_hsld,perc_indig_age_65_over,perc_indig_rent_priv_dwl,perc_indig_rent_pub_dwl,perc_indig_f,perc_indig_owned_outright_dwl,perc_indig_age_35_64,perc_indig_age_15plus_edu_degree_diploma_certificate,perc_indig_hsld_equiv_inc_1000_1500,perc_indig_1_or_more_vehicle_in_hsld,perc_indig_hsld_equiv_inc_above_1500,perc_indig_hsld_equiv_inc_300_1000,sa2_code16,perc_indig_m,perc_indig_age_15_34,perc_indig_age_15plus_edu_none
0,43.157894,17.041801,1.166181,9.302325,2.894737,44.023323,16.034985,49.061660,3.790087,19.210526,30.941704,21.543407,90.697680,3.858521,57.556270,403041087,50.938340,34.736843,12.107623
1,38.823530,10.526316,0.000000,7.894737,10.588235,29.729730,18.918919,36.585365,12.162162,25.882353,27.868853,15.789474,92.105260,19.298246,54.385963,402051049,63.414635,24.705883,21.311476
5,27.941177,17.241379,0.000000,5.970149,11.764706,27.118645,6.779661,44.927536,23.728813,25.000000,26.000000,6.896552,94.029854,0.000000,75.862070,405011114,55.072464,35.294117,18.000000
7,35.593220,5.660378,0.000000,0.000000,11.864407,33.846153,0.000000,43.939392,20.000000,22.033897,39.534885,20.754717,100.000000,0.000000,73.584910,405011110,56.060608,30.508474,6.976744
8,28.571428,4.444445,0.000000,3.092783,14.285714,26.041666,3.125000,43.396225,10.416667,24.489796,26.470589,17.777779,96.907220,5.555555,72.222220,405011111,56.603775,32.653060,8.823529

In [9]:
node_degree_entropy_df = pd.read_pickle('../../data_process/node_degree_entropy_df.pickle')

In [ ]:
node_degre